# Import SConstruct environment.
#
Import('env')

# Import tested library name.
#
Import('BE_TESTED_LIB')

# CxxTests - grab all "*.t.hpp" and build a test program for each of them.
#
test_suite_sources = env.Glob('unit/*.t.hpp')

# A binary is built for every ".t.hpp"
# The name of the image is derived from the source by stripping it's
# extension.
for f in test_suite_sources:
	env.CxxTest( str(f)[:-6], f, LIBS = [BE_TESTED_LIB] )

# A single binary is built which will run all test suites.
#env.CxxTest( "multi", test_suite_sources, LIBS = [BE_TESTED_LIB] )
