# Setup the environvent exported to conscripts.
#
env = Environment(tools = ['default', ('cxxtest', {'CXXTEST_SUFFIX':'.t.hpp'})])
env.Append(CCFLAGS = ' -g -Wall')
Export('env')

# Invoke conscript library under test.
#
BE_TESTED_LIB = SConscript(['src/lib/SConscript'])

# Prepare environment for tests program's conscript.
#     - Library's lib path is added to the linker's search path.
#     - Library's include is added to the compilers's search path.
#     - Library name is exported. 
#
env = env.Clone(
	LIBPATH = '#src/lib',
	CPPPATH = '#src')
Export('env BE_TESTED_LIB')

# Invoke conscript for tests programs.
#
SConscript(['src/tests/SConscript'])
